### ISSUE TITLE
serialport示例打包后，打开应用出错

### ISSUE THREAD

**Issue by FarmersReact** [caoxiemeihao/electron-vite-samples#8]
<img width="520" alt="image" src="https://github.com/caoxiemeihao/electron-vite-samples/assets/50646999/9e00d0f7-5ad4-48d5-b914-187e0fe0dcfb">

Error: Cannot find module '@serialport/parser-byte-length'
Require stack:

**Comment by FarmersReact** [comment]
大佬打扰了，之前用pnpm install的，现在用npm不会出现这个问题了 [捂脸]

**Comment by caoxiemeihao** [comment]
打扫一次 V我50 我原谅你 👀

**Comment by caoxiemeihao** [comment]
打扰一次 V我50￥ 我原谅你 👀
